title = "T.I.L."
baseURL = "https://til.marcusnoble.co.uk"
languageCode = "en-gb"
theme = "hello-friend-ng"
enableGitInfo = true

[permalinks]
  posts = "/:title/"


[params]
  gitUrl = "https://git.cluster.fun/AverageMarcus/til/commit/"
